### ISSUE TITLE
$relations and related() method question

### ISSUE THREAD

**Issue by garbinmarcelo** [Tucker-Eric/EloquentFilter#130]
Hello, I'm trying to do a search filter, but I ran into this issue a few hours ago and I was unsure about its use.
In my case I have a table of users and I am using the permission package [spatie/laravel-permission](https://spatie.be/docs/laravel-permission/v3/introduction) where it already has some traits to search the rules of each user.

I was in doubt how to use the `related ` and `public $relations = [];` feature in this case.

I have the following search filter:
```php
    public function search($words)
    {
        return $this->whereLike('id', $words, 'or')
                    ->whereLike('username', $words, 'or')
                    ->whereLike('email', $words, 'or');
    }
```

What is the best way to search if the word is the name of the user's rule (in the case coming from the model relationship)?

I added the following code after the last `whereLike` of the above filter:
```php
->orWhereHas('roles', function($query) use ($words){
    $query->where('name', 'LIKE', '%' . $words . '%');
 });
```
I tried to use `whereLike` within the `orWhereHas` function but I was not successful.

Full code:
```php
public function search($words)
{
        return $this->whereLike('id', $words, 'or')
                    ->whereLike('username', $words, 'or')
                    ->whereLike('email', $words, 'or')
                    ->orWhereHas('roles', function($query) use ($words){
                        $query->where('name', 'LIKE', '%' . $words . '%');
                    });
}
```

Could you give me a hand and check if this shape is correct or if there is a better way to use it with your package?

I thank you in advance for your attention and also for this package

**Comment by Tucker-Eric** [comment]
In regards to using the `related` method or `$relations` array, I don't think those will work for your use case. Those methods will append a `whereHas` to the query `filter` is called on so we aren't able to use a nested `orWhereHas`. Trying to use those methods would result in:

```sql
SELECT * FROM users 
WHERE id LIKE '%words%' 
OR WHERE username LIKE '%words%'
OR WHERE email LIKE '%words%'
AND WHERE EXISTS (
 // Exists query
)
```

Where you would want the `OR WHERE EXISTS` query which the `relation()` and `$relations` won't accomplish.

The `QueryBuilder` method that's passed to the closure of `orWhereHas` is an instance of `EloquentBuilder` for the `Role` model and since `Role` doesn't have the `Filterable` trait, it doesn't have access to the `whereLike` method.

I'd say your filter is already ideal for what you're looking to accomplish.

**Comment by garbinmarcelo** [comment]
Okay, got it. It was a doubt that I would like to take away and you returned it to me. thank you very much
