### ISSUE TITLE
Combine filter by related and own fields

### ISSUE THREAD

**Issue by git-itmailbox** [Tucker-Eric/EloquentFilter#140]
Hi, can you help with such issue, assume that  we have some entity i.e. User, it has relation hasMany Orders, order belongs to some AnotherEntity.
So I need to filter AnotherEntity by user's name, email, phone and also by AnotherEntity's field (i.e. name).

```php
public $relations = [
    'order.user' => [
        'user_search'  => 'search',
    ]
];


public function search($search)
{
     //so here I need somehow to combine  'user_search' and another additional filter by own field or even another relation
}
```

**Comment by Tucker-Eric** [comment]
If I'm understanding correctly you should be able to leave that as is and it should work. The `$relations` array will forward the `user_search` parameter to `search` in the `UserFilter` and then you can add methods locally on `AnotherEntity` model to filter on `AnotherEntity`.

**Comment by git-itmailbox** [comment]
I'd like to have filter like this one
```
public $relations = [
    'order.user' => [
        'user_search'  => 'search',
    ]
];

public function search($search)
{
     //so here I need somehow to combine  'user_search' and another additional filter by own field or even another relation
    return $this->userSearch($search)
                      ->name($search); //name of AnotherEntity
}

public function name($search)
{
    return $q->where('name', 'LIKE', "%$name%");
}

```

and ofcourse conditions must be connected with OR operator

**Comment by Tucker-Eric** [comment]
So this is kind of tricky in the filter because when using the [`$relations`](https://github.com/Tucker-Eric/EloquentFilter#filter-related-models-using-the-relations-array) array or [`related`](https://github.com/Tucker-Eric/EloquentFilter#filter-related-models-with-the-related-method) method they both collect all calls to each related entity and nest all those in one root level `whereHas` query so combining either of those methods with an `or` could potentially lead to unexpected behavior when adding more parameters that would chain with `and` queries. 

I would suggest to not use the `$relations` array or `related()` method for this use case and use a nested `where` query where you can join with an `or`.

So, given the query to `AnotherEntity`:
```php
AnotherEntity::filter([
	'search'      => 'some_string',
	'user_search' => 'user_string'
])
->get()
```
And the `AnotherEntityModelFilter` to search both strings with an `OR` condition:
```php
public function search($search)
{
    return $this->where(function($query) {
    	$query->whereHas('order.users', function($q) {
    		// $q is an instance of the User query builder
    		// so it has access to the UserModelFilter
    		// allowing us to call `filter` on it
    		$q->filter([
    			'search' => $this->input('user_search')
    		]);
    	})
    	->whereLike('name', $search, 'or');
    });
}
```

**Comment by git-itmailbox** [comment]
thanks, will try your solution. @Tucker-Eric
