### ISSUE TITLE
Logical operator OR instead of AND

### ISSUE THREAD

**Issue by lilian21** [Tucker-Eric/EloquentFilter#29]
Hello guys,
 Very nice package, I'm coming from a RoR environment where filters are there out of the box, I really needed them here also.
 My issue is more like a question: is it possible to use the OR logical operator between queries instead of AND?

Thank you,
Lilian

**Comment by Tucker-Eric** [comment]
You can use OR in a few different ways:

- Use `or` as the last parameter in the [`where()`](https://github.com/laravel/framework/blob/5.4/src/Illuminate/Database/Query/Builder.php#L497) method:

```php
$query->where('name', '=', 'Lilian', 'or');
```

- User the [`orWhere()`](https://github.com/laravel/framework/blob/5.4/src/Illuminate/Database/Query/Builder.php#L641) method:

```php
$query->orWhere('name', '=', 'Lilian');
// Can also omit the '=' operator in the where method
$query->orWhere('name', 'Lilian');
```
Same goes for the `whereIn()` method:

```php
$query->whereIn('my_column', ['prop1', 'prop2'], 'or');
// Also orWhereIn
$query->orWhereIn('my_column', ['prop1', 'prop2']);
```

You can also use the above with subqueries:

```php
$query->where(function($query) use ($companyId) {
    return $query->where('role', 'admin')
        ->where('company_id', $companyId);
})->orWhere(function($query) {
    return $query->where('role', 'super_admin');
});
// Will result in:
SELECT * FROM `table` WHERE (`role` = 'admin' AND `company_id` = $companyId) OR (`role` = 'super_admin');
```

When writing and debugging queries the `toSql()` method is super helpful.  Just call it at the end of a query and it will return the sql statement like:

```php
$query->where(function($query) use ($companyId) {
    return $query->where('role', 'admin')
        ->where('company_id', $companyId);
})->orWhere(function($query) {
    return $query->where('role', 'super_admin');
})->toSql();
```

Another feature is the query log.  Call `\DB::enableQueryLog();` before you run your statement.  Then after the statement call `\DB::getQueryLog();` and it will return all queries ran since you called `\DB::enableQueryLog()`

Most methods are built like this to be able to do this.  If you have a question on whether a method can be written with an `'or'` operator you can always reference the [api documentation](https://laravel.com/api/master/Illuminate/Database/Query/Builder.html)

Hope this helps!
