### ISSUE TITLE
Using Passport with EloquentFilter

### ISSUE THREAD

**Issue by junelmujar** [Tucker-Eric/EloquentFilter#37]
Hi Eric,

Just a quick question, can Laravel Passport work with EloquentFilter and how do you go about it?

Thanks a lot for any input.

Regards,

Junel

**Comment by Tucker-Eric** [comment]
You can have EloquentFilter in the same project as Laravel Passport if that's what you're asking.

If not, then I don't think I understand the integration you're going for?

**Comment by junelmujar** [comment]
Sorry for the confusion, I meant to say Laravel Scout. :) 

Basically I would like to use Model::search('<keyword>') provided by Scout inside a model filter. I've already configured Scout along with a driver mysql.

Thank you.

Regards,

Junel

**Comment by Tucker-Eric** [comment]
You can but since Scout uses a different `Builder` instance you wouldn't be able to apply multiple constraints with the `search` method and `filter()` would return an instance of the `Laravel\Scout\Builder` instead of `Illuminate\Database\Eloquent\Builder`

If I were to suggest an implementation it would be to override the `handle()` method on the filter and in that method check for the existance of your search query parameter to overwrite the filter's query builder so all subsequent calls to filter by input are passed to Scout's query builder and return that or call the parent's `handle()` method to revert back to filter functionality.

The `handle()` method in your model's filter would look like:

```php
public function handle()
{
    if($this->input('q')) {
        // Overwrite the query builder with Scout's builder
        $this->query = forward_static_call([$this->getModel(), 'search'], $this->input('q'));
        // Apply all the filterable input to Sout's query builder
        $this->filterInput();

        return $this->query;
    }
    
    return  parent::handle();
}
```

So on your model to implement `search()` using `filter()` all you would need to do is:
```php
Model::filter(['q' => 'search string', 'active' => 1])->get();
```

**Comment by junelmujar** [comment]
Thanks a lot!

Regards,

Junel
