### ISSUE TITLE
There is a way to filter a related model which have the same fields ?

### ISSUE THREAD

**Issue by symoo** [Tucker-Eric/EloquentFilter#53]
Hi Eric:
Thanks for your excellence lib. 
just like I mention in the title,
what if the Client model and the User model both have a filed named 'title', 
```
class UserFilter extends ModelFilter
{
    public $relations = [
        'clients' => ['title', 'potential_volume'],
    ];
}
public function title($title)
{
   return $this->whereLike('title', $title);
}
}

class ClientFilter extends ModelFilter
{
    public $relations = [];

 public function title($title)
{
   return $this->whereLike('title', $title);
}
    
}
```
How can they work?

**Comment by Tucker-Eric** [comment]
Although using the `$relations` array is still supported I'd advise using the [`related()`](https://github.com/Tucker-Eric/EloquentFilter/wiki/Filtering-By-Relationships#filter-related-models-with-the-related-method) method instead for all relations.

However your example would technically work when using `UserFilter` and `title` would be passed to `UserFilter::title` and to `ClientFilter::title`

To use the `related()` method in your case you would do:
```php
class UserFilter extends ModelFilter
{
    public $relations = [];

    public function title($title)
    {
       return $this->whereLike('title', $title)->related('clients', 'title', $title);
    }

    public function potentialVolume($volume)
    {
        return $this->related('clients', 'potential_volume', $volume);
    }
}
```

Which would also remove the need to have a `ClientFilter` because the `related()` method constrains by the related model directly instead of relying on the related model to have a model filter.

**Comment by symoo** [comment]
Good to know ! 
Thanks a lot !
