### ISSUE TITLE
Use filter set up in relationship's filter

### ISSUE THREAD

**Issue by kyleweishaupt** [Tucker-Eric/EloquentFilter#69]
I'm trying to filter my `cases` model by `patient`, in which both have their own filters respectively. In my `patient` filter, I have the following filter I'd like to re-use if possible:
```php
class PatientFilter extends ModelFilter
{
    public function name($name)
    {
        return $this->where('first_name', 'LIKE', DB::getPdo()->quote($name . '%'))
            ->orWhere('last_name', 'LIKE', DB::getPdo()->quote('%' . $name . '%'))
            ->orWhereRaw('concat([first_name], \' \', [last_name]) LIKE ' . DB::getPdo()->quote('%' . $name . '%'));
    }
}
```
I'm trying to access this filter from within my `CaseEntityFilter` class so I can pass something like `patient_name` as a filter on the case and return cases matching the patient name. 

Here's what I've tried for the filter on cases, but to no luck:
```php
class CaseEntityFilter extends ModelFilter
{
    // Cant seem to get this to point to the method on the actual filter
    public $relations = [
        'patient' => [
            'name',
            'firstName',
            'patient_name'
        ]
    ];

    // Produces 'invalid column' error
    public function patientName($name)
    {
        return $this->related('patient', 'name', $name);
    }
```
My database (SQL Server) throws an error about the column `name` not existing (which it rightfully doesn't). I can't seem to figure out how to execute the name() method on my patient's filter instead of just querying for the column 'name'.

I'm new to Laravel so is there something I'm missing or would this be considered a feature request? 

Thank you for the excellent plugin by the way! :)

**Comment by Tucker-Eric** [comment]
They way you have this set up, if you pass a `name` parameter to your `CaseEntityFilter` it will automatically forward that to the `name` method on `PatientFilter` because `name` is present in your `$relations['patient']` array. That array is also setup to forward a `firstName` parameter to `PatientFilter::firstName()` (if it exists) and `patient_name` to `PatientFilter::patientName()` (if it exists) without having to define any methods on `CaseEntityFilter`.

If you want to use a `patient_name` parameter to call a `patientName()` method on your `CaseEntityFilter` that will call the `name()` on `PatientFilter` then you can do it like:

```php
class CaseEntityFilter extends ModelFilter
{
    // Cant seem to get this to point to the method on the actual filter
    public $relations = [
        'patient' => [
            'name',
            'firstName'
        ]
    ];

    public function patientName($name)
    {
        return $this->related('patient', function($query) use ($name) {
            // $query here is an instance of the `patient` relation's query builder
            return $query->filter(['name' => $name]);
        });
    }
```

**Comment by kyleweishaupt** [comment]
Aha. The `$query->filter()` portion was exactly what I was looking for. Thanks again!
