### ISSUE TITLE
Using OR with related method for Joins

### ISSUE THREAD

**Issue by yogeshwaran-manoharan** [Tucker-Eric/EloquentFilter#81]
Hello there, I've using this package for filters and it works perfectly. I have a scenario where `related` method should be used with `or` instead of `and`.  No reference in docs too. Is there any way i can make it work?

**Comment by Tucker-Eric** [comment]
This is possible but it depends on where that `OR` is located. The `related($relation)` method aggregates all calls and then passes them in a `whereHas($relation)` call to the related model so if you're talking about adding an `or` inside the `whereHas()` you can do:

```php
public function thingCol1($val)
{
    $this->related('thing', 'col_1', '=', $val, 'or');
}

public function thingCol2($val)
{
    $this->related('thing', 'col_2', '=', $val, 'or');
}
```
This is the same as doing
```php
public function thingCol1($val)
{
    $this->whereHas('thing', function($query) use ($val) {
        return $query->where('col_1', '=', $val)
            ->orWhere('col_2', '=', $this->input('thing_col_2'));
    });
}
```

But if you want the actual `whereHas` to use `or` as in `orWhereHas()` which would put that `or` on the parent query, instead of the related subquery like above, then you would need to call that directly.  If your related model has a filter you could just pass the input to that filter like:

```php
public function thing()
{
    $this->orWhereHas('thing', function($query) {
        // Keys from input to pass to the related filter
        $thing_cols = ['thing_col_1', 'thing_col_2'];
        // $query here is an instance of 'thing's query builder
        // Extract just the desired columns from the input and filter on related model's filter
        $query->filter(array_only($this->input(), $thing_cols));
        // Blacklist all the input's that are used here to avoid this method being called multiple times.
        foreach ($thing_cols as $col) {            
            $this->blacklistMethod($this->getFilterMethod($col));
        }

        return $query;
    });
}

public function thingCol1($val)
{
    $this->thing();
}

public function thingCol2($val)
{
    $this->thing();
}
```
